run-name: Gama benchmarking

on:
  workflow_dispatch:

env:
  JAVA_HOME: /opt/gama-platform/jdk
#  PATH: ${{ env.JAVA_HOME }}/bin:${{ env.PATH }}

jobs:
  benchmark:
    name: Benchmarking
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Gama
        shell: bash
        working-directory: /tmp
        run: |
          wget --show-progress https://github.com/gama-platform/gama/releases/download/1.9.1/GAMA_1.9.1_Linux_with_JDK.deb 
          sudo dpkg -i GAMA_1.9.1_Linux_with_JDK.deb
          PATH="$PATH:/opt/gama-platform/jdk/bin"

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.7.1
        with:
          gradle-version: current

      - name: Run Models in gama-workspace
        working-directory: JMX
        shell: bash
        run: |
          TARGET_EQUINOX_CP=$(ls /opt/gama-platform/plugins/org.eclipse.equinox.launcher*.jar)
          
          gradle run \
            --args="java -cp $TARGET_EQUINOX_CP -Djava.awt.headless=true org.eclipse.core.launcher.Main -application msi.gama.headless.product" \
            | grep "Result File:" | cut -d':' -f2
